# Generated by Django 5.1.7 on 2025-03-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='student.jog', upload_to='student_pictures'),
        ),
    ]
