# Generated by Django 5.1.7 on 2025-03-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-03-15'),
            preserve_default=False,
        ),
    ]
