# Generated by Django 5.1.7 on 2025-03-15 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
